name: survlift2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - astor=0.8.1
  - autograd=1.7.0
  - autograd-gamma=0.5.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cached_property=1.5.2
  - cairo=1.18.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - double-conversion=3.3.0
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - formulaic=1.1.1
  - freetype=2.12.1
  - graphite2=1.3.13
  - graphlib-backport=1.0.3
  - harfbuzz=10.2.0
  - icu=75.1
  - interface_meta=1.3.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.2
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lifelines=0.30.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.44
  - pip=24.3.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pyparsing=3.2.1
  - pyside6=6.8.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.8.1
  - readline=8.2
  - scipy=1.15.2
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.6
  - pip:
    - accelerate==1.7.0
    - bitsandbytes==0.43.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - filelock==3.18.0
    - fsspec==2025.5.1
    - hf-xet==1.1.2
    - huggingface-hub==0.32.1
    - idna==3.10
    - jinja2==3.1.6
    - joblib==1.5.1
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.9.41
    - nvidia-nvtx-cu12==12.1.105
    - patsy==1.0.1
    - peft==0.8.2
    - pillow==11.2.1
    - psutil==7.0.0
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - scikit-learn==1.3.2
    - setuptools==80.9.0
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tokenizers==0.21.1
    # - torch==2.5.1+cu121
    # - torchaudio==2.5.1+cu121
    # - torchvision==0.20.1+cu121
    - tqdm==4.66.2
    - transformers==4.52.3
    - triton==3.1.0
    - typing-extensions==4.13.2
    - urllib3==2.4.0
